apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-site
  labels:
    app: html-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-site
  template:
    metadata:
      labels:
        app: html-site
    spec:
      containers:
        - name: html-site
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPOSITORY_NAME>:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-site-service
spec:
  type: LoadBalancer
  selector:
    app: html-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

