name: Deploy Static Site to EKS

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          # Build the Docker image
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest .
          # Push the Docker image to ECR
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Set up Kubeconfig
        uses: aws-actions/configure-kubeconfig@v2  # Corrected to v2
        with:
          region: ${{ secrets.AWS_REGION }}
          cluster-name: SampleEKSCluster

      - name: Deploy Static Site with Helm to EKS
        run: |
          helm upgrade --install static-site ./nginx-helm --namespace default \
            --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }} \
            --set image.tag=latest \
            --set service.type=LoadBalancer

      - name: Wait for LoadBalancer to be ready
        run: |
          kubectl wait --for=condition=available --timeout=600s deployment/static-site -n default
          kubectl get svc static-site -n default
